### PR TITLE
Exception on invalid JSON or unknown field in genesis configuration

### LINKED ISSUE #4514: genesis configuration parsing should fail when there is an unknown field
There was a misspelled option "startBlock" in many genesis configuration files: https://github.com/ethereum/cpp-ethereum/pull/4513

In order to detect these at least at runtime, the genesis configuration parsing should fail when it sees an unknown field.

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #4514.

### CODE REVIEW

File: libethereum/ChainParams.cpp [hunk 1]
```diff
@@ -115,19 +205,22 @@ ChainParams ChainParams::loadGenesis(string const& _json, h256 const& _stateRoot
...
-	cp.parentHash = h256(genesis["parentHash"].get_str());
-	cp.author = genesis.count("coinbase") ? h160(genesis["coinbase"].get_str()) : h160(genesis["author"].get_str());
-	cp.difficulty = genesis.count("difficulty") ? u256(fromBigEndian<u256>(fromHex(genesis["difficulty"].get_str()))) : 0;
-	cp.gasLimit = u256(fromBigEndian<u256>(fromHex(genesis["gasLimit"].get_str())));
-	cp.gasUsed = genesis.count("gasUsed") ? u256(fromBigEndian<u256>(fromHex(genesis["gasUsed"].get_str()))) : 0;
-	cp.timestamp = u256(fromBigEndian<u256>(fromHex(genesis["timestamp"].get_str())));
-	cp.extraData = bytes(fromHex(genesis["extraData"].get_str()));
+	validateGenesis(genesis);
+
+	// TODO: check for unknown fields
```
Comment (winsvega) [inline libethereum/ChainParams.cpp]: so this comment could be removed

**Comment by pirapira** [comment]
The failure in AppVeyor looks real.

File: test/unittests/libethereum/BlockChain.cpp [hunk 2]
```diff
@@ -389,4 +390,18 @@ BOOST_AUTO_TEST_CASE(updateStats)
...
+{
+	h256 emptyStateRoot;
+	/* Below, a comma is missing between fields. */
+	BOOST_CHECK_THROW(ChainParams("{ \"sealEngine\" : \"unknown\" \"accountStartNonce\" : \"3\" }", emptyStateRoot), json_spirit::Error_position);
+}
+
+BOOST_AUTO_TEST_CASE(unknownFieldThrows)
+{
+	h256 emptyStateRoot;
+	/* Below, a comma is missing between fields. */
```
Comment (gumb0) [inline test/unittests/libethereum/BlockChain.cpp]: this comment is not true

File: libethereum/ChainParams.cpp [hunk 3]
```diff
@@ -51,50 +51,113 @@ ChainParams::ChainParams(string const& _json, h256 const& _stateRoot)
 	*this = loadConfig(_json, _stateRoot);
 }
 
+string const c_str_sealEngine = "sealEngine";
```
Comment (gumb0) [inline libethereum/ChainParams.cpp]: Put all these globals and functions into anonymous namespace

File: libethereum/Account.cpp [hunk 4]
```diff
@@ -81,6 +81,50 @@ PrecompiledContract createPrecompiledContract(js::mObject& _precompiled)
 }
 
 }
+namespace
+{
+	string const c_str_wei = "wei";
```
Comment (gumb0) [inline libethereum/Account.cpp]: I don't using underscores here other than for `c_` prefix. I'd prefer these to be `c_strWei` or just `c_wei` etc.
Also `c_knownAccountFields `

**Comment by winsvega** [comment]
@pirapira  please rebase both this PR an the test repo on develop

**Comment by pirapira** [comment]
Addressed all comments so far.

File: libethereum/ChainParams.cpp [hunk 5]
```diff
@@ -107,6 +173,36 @@ ChainParams ChainParams::loadGenesisState(string const& _json, h256 const& _stat
...
+		c_extraData, c_mixHash, c_nonce
+	};
+
+	void validateGenesis(js::mObject const& _genesis)
+	{
+		for (auto const& elm: _genesis)
+			if (c_knownGenesisFields.find(elm.first) == c_knownGenesisFields.end())
+			{
+				string const comment = "Unknown field in genesis config[genesis]: " + elm.first;
+				cerr << comment << "\n";
```
Comment (gumb0) [inline libethereum/ChainParams.cpp]: Do we need this? Wouldn't exception handler output it, too, since we add it to exception?

File: libethereum/ChainParams.cpp [hunk 6]
```diff
@@ -51,50 +51,116 @@ ChainParams::ChainParams(string const& _json, h256 const& _stateRoot)
 	*this = loadConfig(_json, _stateRoot);
 }
 
+namespace
+{
+	string const c_sealEngine = "sealEngine";
```
Comment (gumb0) [inline libethereum/ChainParams.cpp]: Usually we don't indent what's inside the namespace

File: libethereum/ChainParams.cpp [hunk 7]
```diff
@@ -51,50 +51,116 @@ ChainParams::ChainParams(string const& _json, h256 const& _stateRoot)
...
+
+	set<string> const c_knownParamNames = {
+		c_minGasLimit, c_maxGasLimit, c_gasLimitBoundDivisor, c_homesteadForkBlock,
+		c_EIP150ForkBlock, c_EIP158ForkBlock, c_accountStartNonce, c_maximumExtraDataSize,
+		c_tieBreakingGas, c_blockReward, c_byzantiumForkBlock, c_constantinopleForkBlock,
+		c_daoHardforkBlock, c_minimumDifficulty, c_difficultyBoundDivisor, c_durationLimit,
+		c_chainID, c_networkID, c_allowFutureBlocks, c_registrar
+	};
+
+	void validateParams(js::mObject const& _params)
```
Comment (gumb0) [inline libethereum/ChainParams.cpp]: Well, this is repetition. How about making one function like `validateFields(jsObject const& _obj, std<string> const& _allowedFields)`?

File: libethereum/Account.cpp [hunk 8]
```diff
@@ -81,6 +81,50 @@ PrecompiledContract createPrecompiledContract(js::mObject& _precompiled)
...
+	string const c_nonce = "nonce";
+	string const c_code = "code";
+	string const c_storage = "storage";
+	string const c_shouldnotexist = "shouldnotexist";
+	string const c_precompiled = "precompiled";
+	std::set<string> const c_knownAccountFields = {
+		c_wei, c_finney, c_balance, c_nonce, c_code, c_storage, c_shouldnotexist,
+		c_code, c_precompiled
+	};
+	void validateAccount(js::mObject const& o)
```
Comment (gumb0) [inline libethereum/Account.cpp]: `_o`

File: libethereum/ChainParams.cpp (hunk 7 above)
Comment (pirapira) [reply libethereum/ChainParams.cpp]: Good idea.

File: libethereum/Account.cpp (hunk 8 above)
Comment (pirapira) [reply libethereum/Account.cpp]: OK.

File: libethereum/ChainParams.cpp (hunk 5 above)
Comment (pirapira) [reply libethereum/ChainParams.cpp]: The exception handler currently does not output it. The handler is somewhere in boost_test.

File: libethereum/Account.cpp [hunk 9]
```diff
@@ -81,6 +81,50 @@ PrecompiledContract createPrecompiledContract(js::mObject& _precompiled)
...
+		for (auto const& account: o)
+			validateAccount(account.second.get_obj());
+	}
+	string const c_alloc = "alloc";
+	string const c_accounts = "accounts";
+	void validateAccountMapObj(js::mObject const& o)
+	{
+		for (auto const& field: o)
+		{
+			if (field.first == c_alloc)
```
Comment (gumb0) [inline libethereum/Account.cpp]: This I guess can be simplified to `if (field.first == c_alloc || field.first == c_accounts)`

Comment (gumb0) [reply libethereum/Account.cpp]: Also, does anyone still uses these `alloc` and `account` options?

**Comment by gumb0** [comment]
Some improvement suggestions but in general looks good.

File: libethereum/Account.cpp (hunk 9 above)
Comment (pirapira) [reply libethereum/Account.cpp]: I tried removing these.

File: libdevcore/JsonUtils.cpp [hunk 10]
```diff
@@ -0,0 +1,33 @@
...
+	along with cpp-ethereum.  If not, see <http://www.gnu.org/licenses/>.
+*/
+
+#include <libdevcore/JsonUtils.h>
+#include <json_spirit/JsonSpiritHeaders.h>
+#include <set>
+#include <string>
+#include <ostream>
+
+void dev::validateFieldNames(json_spirit::mObject const& _obj, std::set<std::string> const& _allowedFields)
```
Comment (winsvega) [inline libdevcore/JsonUtils.cpp]: could we do a function like this to validate test fillers for unknown fields?
or do you think that json scheme on tests repo is enough?

Comment (pirapira) [reply libdevcore/JsonUtils.cpp]: I think the Json scheme on test repo is enough.

**Comment by pirapira** [comment]
The AppVeyor failure should be fixed after rebased on https://github.com/ethereum/cpp-ethereum/pull/4532

**Comment by pirapira** [comment]
Rebased.
