### PR TITLE
Defer element removal after iteration

### LINKED ISSUE #4316: testeth --filltests --fillchain --singletest fails finding an empty file
`ETHEREUM_TEST_PATH="../../tests" ./test/testeth -t 'StateTestsGeneral' -- --filltests --checkstate --fillchain --singletest returndatacopy_following_revert`

causes

```
/home/yh/src/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(512): error: in "StateTestsGeneral/stReturnDataTest": returndatacopy_following_revert_d0g0v0_Constantinople Failed filling test with Exception: std::bad_alloc
/home/yh/src/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(522): fatal error: in "StateTestsGeneral/stReturnDataTest": Contents of ../../tests/BlockchainTests/GeneralStateTests/stReturnDataTest/returndatacopy_following_revert_d0g0v0.json is empty. Have you cloned the 'tests' repo branch develop and set ETHEREUM_TEST_PATH to its path?
```

If I remove `--fillchain`, the command works.

### PR DESCRIPTION
**Pull request by pirapira**
A loop in BlockChainTest.cpp removed an elment from a container while iterating through it.
Apparently this caused some memory corruption. Without this fix, I saw a testname.size() more than 100MB.

Fixes #4316

### CODE REVIEW

**Comment by winsvega** [comment]
need to check how this work with --filltests  and --filltests --fillchain

**Comment by pirapira** [comment]
I used those for filling https://github.com/ethereum/tests/pull/255

**Comment by pirapira** [comment]
The Appveyor failure looks like Hunter related.  I've pinged @chfast.

**Comment by chfast** [comment]
Rebase to fix the build.

File: test/tools/jsontests/BlockChainTests.cpp [hunk 1]
```diff
@@ -205,8 +207,9 @@ void doBlockchainTestNoLog(json_spirit::mValue& _v, bool _fillin)
 				tests[newtestname] = jObj;
 			}
 
-			//delete source test from the json
-			_v.get_obj().erase(_v.get_obj().find(testname));
```
Comment (chfast) [inline test/tools/jsontests/BlockChainTests.cpp]: Do you remove the current item? If yes, you should keep the iterator somewhere and use the common pattern: https://stackoverflow.com/questions/8234779/how-to-remove-from-a-map-while-iterating-it.

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: That's a good idea.

Comment (winsvega) [inline test/tools/jsontests/BlockChainTests.cpp]: So which method is better. A removeList  or pattern with extra iterator?

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: I'm trying the `it = erase(it)` way.

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: Now I like https://stackoverflow.com/a/39719450/103518

Comment (winsvega) [inline test/tools/jsontests/BlockChainTests.cpp]: this does not work with json. I had to use removeList method.

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: looks like so.  My test filling does not terminate with `it = erase(it)` way somehow.

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: So, I now store iterators in a remove list.

**Comment by pirapira** [comment]
Appveyor is still experiencing some hunter or cmake problem.  Rebasing.

File: test/tools/jsontests/BlockChainTests.cpp (hunk 1 above)
Comment (chfast) [inline test/tools/jsontests/BlockChainTests.cpp]: I'm only suggesting a pattern I know. Using iterators is always better, because they are the quickest way. Remove list is another data structure and you have to do the find again.

**Comment by chfast** [comment]
Rebased helped. I messed up Hunter cache a bit, but Hunter maintainer promised it will not happen again unless I repeat the mistakes again.

**Comment by pirapira** [comment]
@chfast please review again

File: test/tools/jsontests/BlockChainTests.cpp [hunk 2]
```diff
@@ -221,6 +225,10 @@ void doBlockchainTestNoLog(json_spirit::mValue& _v, bool _fillin)
 		}
 	}
 
+	//Delete source test from the json
+	for (auto i: erase_list)
+		_v.get_obj().erase(i);
```
Comment (chfast) [inline test/tools/jsontests/BlockChainTests.cpp]: I realized this is actually wrong. `erase()` invalidates map iterators, so only the first erase is ok, then you have the vector of invalid iterators. If the erase list to be used, it must contain map keys, not iterators.

Comment (pirapira) [inline test/tools/jsontests/BlockChainTests.cpp]: Not in a map, I read https://stackoverflow.com/a/263958/103518.  Maybe I need to check better references.

Comment (chfast) [inline test/tools/jsontests/BlockChainTests.cpp]: Yes, you are right. I was reading it wrong. Only the erased iterator is invalidated.
