### PR TITLE
Fix gas for builtin.

### LINKED ISSUE #1300: AlethZero crashes when parsing solidity contract
example code:

```
contract main
{
       function method () returns (bool)
       {
		if (ripemd160.gas(200000) ('teststring', 200000) != 0xcd566972b5e50104011a92b59fa8e0b1234851ae)		
			return false;
       }
}
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #1300

### CODE REVIEW

File: test/SolidityEndToEndTest.cpp [hunk 1]
```diff
@@ -1647,6 +1647,21 @@ BOOST_AUTO_TEST_CASE(gas_and_value_basic)
 	BOOST_REQUIRE(callContractFunction("checkState()", 5) == encodeArgs(false, 20 - 5));
 }
 
+BOOST_AUTO_TEST_CASE(gas_for_builtin)
+{
+	char const* sourceCode = R"(
+		contract Contract {
+			function test(uint g) returns (hash data, bool flag) {
```
Comment (LefterisJP) [inline test/SolidityEndToEndTest.cpp]: `hash` -> `bytes32`

**Comment by chriseth** [comment]
Waiting for tests.
