### PR TITLE
Revendoring ethash

### LINKED ISSUE #1253: Vendored Ethash Has Wrong Data Sizes
See data sizes set upstream:

https://github.com/ethereum/ethash/blob/master/src/libethash/data_sizes.h

### PR DESCRIPTION
**Pull request by xcthulhu**
Revendoring ethash based on Rev 23

Closes #1253

### CODE REVIEW

**Comment by gavofyork** [comment]
Does this bring us into compatibility with Go?

File: libethash/ethash.h [hunk 1]
```diff
@@ -25,26 +26,17 @@
...
-#define ETHASH_DAGSIZE_BYTES_INIT 1073741824U // 2**30
-#define ETHASH_DAG_GROWTH 113000000U
-#define ETHASH_EPOCH_LENGTH 30000U
-#define ETHASH_MIX_BYTES 128
-#define ETHASH_DAG_PARENTS 256
-#define ETHASH_CACHE_ROUNDS 3
-#define ETHASH_ACCESSES 64
-
-// *********************
-// TODO: Remove once other code moved over to compliant naming scheme.
```
Comment (gavofyork) [inline libethash/ethash.h]: how rude.

don't just clobber if you don't like. the naming scheme is there for a reason.

File: libethash/data_sizes.h [hunk 2]
```diff
@@ -33,213 +31,780 @@ extern "C" {
...
+//         HashBytes = 64,
+//         CacheMultiplier = 1024,
+//         j = 0},
+//     Reap[
+//       While[j < n,
+//        Module[{i = Floor[(DataSetSizeBytesInit + DataSetGrowth * j) / (CacheMultiplier * HashBytes)]},
+//         While[! PrimeQ[i], i--];
+//         Sow[i*HashBytes]; j++]]]][[2]][[1]]
+
+const size_t cache_sizes[2048] = {
```
Comment (gavofyork) [inline libethash/data_sizes.h]: hard-coding this is utterly horrible. prefer to provide the function to calculate it alongside the data.

File: libethash/data_sizes.h [hunk 3]
```diff
@@ -33,213 +31,780 @@ extern "C" {
...
+//       Reap[
+//         While[j < n,
+//           Module[{i =
+//             Floor[(CacheSizeBytesInit + CacheGrowth * j) / HashBytes]},
+//             While[! PrimeQ[i], i--];
+//             Sow[i*HashBytes]; j++]]]][[2]][[1]]
+
+
+static const size_t dag_sizes[2048] = {
+        1073739904U, 1082130304U, 1090514816U, 1098906752U, 1107293056U,
```
Comment (gavofyork) [inline libethash/data_sizes.h]: hard-coding this is utterly horrible. prefer to provide the function to calculate it alongside the data.
