### PR TITLE
Resolve GCC 7+ warnings

### LINKED ISSUE #4115: Compilation fails with GCC 7
using Fedora 26, which has _gcc (GCC) 7.1.1 20170526_ when following the instructions for building I get the following when running make:

```bash
Scanning dependencies of target ethash
[ 28%] Building C object libethash/CMakeFiles/ethash.dir/io.c.o
[ 28%] Building C object libethash/CMakeFiles/ethash.dir/internal.c.o
/home/singingbush/cpp-ethereum/libethash/internal.c: In function ‘ethash_full_new_internal’:
/home/singingbush/cpp-ethereum/libethash/internal.c:472:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if (ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, true) != ETHASH_IO_MEMO_MISMATCH) {
      ^
/home/singingbush/cpp-ethereum/libethash/internal.c:477:2: note: here
  case ETHASH_IO_MEMO_MISMATCH:
  ^~~~
cc1: all warnings being treated as errors
make[2]: *** [libethash/CMakeFiles/ethash.dir/build.make:87: libethash/CMakeFiles/ethash.dir/internal.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:495: libethash/CMakeFiles/ethash.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

### PR DESCRIPTION
**Pull request by Dar13**
Fixes #4115 

Biggest change here was the reworking of the switch statement in ethash_full_new_internal into a series of if-statements to avoid the need for switch-statement fall-through.

### CODE REVIEW

File: libethash/internal.c [hunk 1]
```diff
@@ -446,42 +446,48 @@ ethash_full_t ethash_full_new_internal(
...
-		for (uint32_t i = 1; i != countnodes; ++i) {
-			tmp_nodes[i] = ret->data[i];
-		}
-		ret->data = tmp_nodes;
-#endif
-		return ret;
-	case ETHASH_IO_MEMO_SIZE_MISMATCH:
+	}
+
+	if(err == ETHASH_IO_MEMO_SIZE_MISMATCH)
```
Comment (pirapira) [inline libethash/internal.c]: Style: a space is desired between `if` and `(`.

File: libethash/internal.c [hunk 2]
```diff
@@ -446,42 +446,45 @@ ethash_full_t ethash_full_new_internal(
 		return NULL;
 	}
 	ret->file_size = (size_t)full_size;
-	switch (ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, false)) {
-	case ETHASH_IO_FAIL:
-		// ethash_io_prepare will do all ETHASH_CRITICAL() logging in fail case
+
+	enum ethash_io_rc err = ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, false);
+	if (err == ETHASH_IO_FAIL) {
```
Comment (chfast) [inline libethash/internal.c]: Can you just remove the `{}` to be more/less consistent with our C++ code?

Comment (Dar13) [inline libethash/internal.c]: Sure thing
