### PR TITLE
Fix VM ignoring virtual push data

### LINKED ISSUE #3333: Heap-buffer-overflow in interpreter
```
=================================================================
==7284==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200113ca91 at pc 0x7f651250ada2 bp 0x7f64f899c750 sp 0x7f64f899c740
READ of size 1 at 0x60200113ca91 thread T14 (eth)
    #0 0x7f651250ada1 in dev::eth::VM::interpretCases() (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libevm/libevm.so+0x47da1)
    #1 0x7f651250259d in dev::eth::VM::execImpl(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>&, dev::eth::ExtVMFace&, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libevm/libevm.so+0x3f59d)
    #2 0x7f65128ea8d2 in dev::eth::Executive::go(std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x3788d2)
    #3 0x7f651289a708 in dev::eth::State::execute(dev::eth::EnvInfo const&, dev::eth::SealEngineFace*, dev::eth::Transaction const&, dev::eth::Permanence, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x328708)
    #4 0x7f6512743820 in dev::eth::Block::execute(std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > > const&, dev::eth::Transaction const&, dev::eth::Permanence, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1d1820)
    #5 0x7f6512748f4e in dev::eth::Block::enact(dev::eth::VerifiedBlockRef const&, dev::eth::BlockChain const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1d6f4e)
    #6 0x7f651274e5a3 in dev::eth::Block::enactOn(dev::eth::VerifiedBlockRef const&, dev::eth::BlockChain const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1dc5a3)
    #7 0x7f6512854099 in dev::eth::BlockChain::import(dev::eth::VerifiedBlockRef const&, dev::OverlayDB const&, bool) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x2e2099)
    #8 0x7f65128592be in dev::eth::BlockChain::sync(dev::eth::BlockQueue&, dev::OverlayDB const&, unsigned int) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x2e72be)
    #9 0x7f6512708573 in dev::eth::Client::syncBlockQueue() (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x196573)
    #10 0x7f6512708aac in dev::eth::Client::doWork(bool) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x196aac)
    #11 0x7f6511cd67b4 in dev::Worker::startWorking()::{lambda()#1}::operator()() const [clone .constprop.236] (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libdevcore/libdevcore.so+0x8c7b4)
    #12 0x7f6511137c7f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c7f)
    #13 0x7f6512c126f9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76f9)
    #14 0x7f651089db5c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x106b5c)

0x60200113ca91 is located 0 bytes to the right of 1-byte region [0x60200113ca90,0x60200113ca91)
allocated by thread T14 (eth) here:
    #0 0x7f65135a4532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f651252e53f in dev::eth::VM::initEntry() (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libevm/libevm.so+0x6b53f)
    #2 0x7f651250259d in dev::eth::VM::execImpl(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>&, dev::eth::ExtVMFace&, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libevm/libevm.so+0x3f59d)
    #3 0x7f65128ea8d2 in dev::eth::Executive::go(std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x3788d2)
    #4 0x7f651289a708 in dev::eth::State::execute(dev::eth::EnvInfo const&, dev::eth::SealEngineFace*, dev::eth::Transaction const&, dev::eth::Permanence, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x328708)
    #5 0x7f6512743820 in dev::eth::Block::execute(std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > > const&, dev::eth::Transaction const&, dev::eth::Permanence, std::function<void (unsigned long, unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1d1820)
    #6 0x7f6512748f4e in dev::eth::Block::enact(dev::eth::VerifiedBlockRef const&, dev::eth::BlockChain const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1d6f4e)
    #7 0x7f651274e5a3 in dev::eth::Block::enactOn(dev::eth::VerifiedBlockRef const&, dev::eth::BlockChain const&) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x1dc5a3)
    #8 0x7f6512854099 in dev::eth::BlockChain::import(dev::eth::VerifiedBlockRef const&, dev::OverlayDB const&, bool) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x2e2099)
    #9 0x7f65128592be in dev::eth::BlockChain::sync(dev::eth::BlockQueue&, dev::OverlayDB const&, unsigned int) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x2e72be)
    #10 0x7f6512708573 in dev::eth::Client::syncBlockQueue() (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x196573)
    #11 0x7f6512708aac in dev::eth::Client::doWork(bool) (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libethereum/libethereum.so+0x196aac)
    #12 0x7f6511cd67b4 in dev::Worker::startWorking()::{lambda()#1}::operator()() const [clone .constprop.236] (/home/chfast/Projects/ethereum/build/cpp-ethereum/asan/libdevcore/libdevcore.so+0x8c7b4)
    #13 0x7f6511137c7f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8c7f)

Thread T14 (eth) created by T0 here:
    #0 0x7f6513541253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7f6511137dc2 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb8dc2)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 dev::eth::VM::interpretCases()
Shadow bytes around the buggy address:
  0x0c048021f900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048021f910: fa fa fa fa fa fa fa fa fa fa fd fd fa fa fa fa
  0x0c048021f920: fa fa fa fa fa fa 03 fa fa fa fa fa fa fa fa fa
  0x0c048021f930: fa fa fa fa fa fa fd fd fa fa 00 01 fa fa fa fa
  0x0c048021f940: fa fa fa fa fa fa 03 fa fa fa 00 01 fa fa fa fa
=>0x0c048021f950: fa fa[01]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048021f960: fa fa fa fa fa fa 00 01 fa fa fa fa fa fa fa fa
  0x0c048021f970: fa fa fd fa fa fa fa fa fa fa 00 01 fa fa 00 01
  0x0c048021f980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048021f990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048021f9a0: fa fa 00 01 fa fa fa fa fa fa 00 01 fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==7284==ABORTING
```

### PR DESCRIPTION
**Pull request by chfast**
Zerod push data might not be physically in the EVM bytecode. E.g. "60" is valid bytecode and it mean PUSH1(0x00) by interpreting the code as "6000000000000000000000000...".

I fixed that by exceeding the copy of the code made by the VM by 32 zerod bytes. But I'm not sure why this copy is made in the first place. @gcolvin?

Fixes #3333.

### CODE REVIEW

**Comment by gcolvin** [comment]
@chfast Thanks for digging into this.  I assume the PUSH1 near the end of the contract?
@dmitry Do we test for this?
@chriseth

Yes, trailing zeros at the end of the bytecode can be truncated, and need to be added back in, which well might be the problem.  The answer might be to simply remove lines 733-738 in VM.cpp, and a suspicious optimization with it.  I won't able to really work on this until Saturday, after I finally get home.  The fix above does look safe to get us going until the root of the problem is found.

**Comment by chfast** [comment]
There are tests for that. E.g. in VMTests/vmPush[...].json. But it looks the issue is only detectable with address sanitizer.

**Comment by chfast** [comment]
@gcolvin, this PR contains also a fix. Have you seen it?

**Comment by gcolvin** [comment]
Yes @chfast, I studied your fix,.  I think it is a workaround for the fix I suggested.

**Comment by gcolvin** [comment]
@chfast  @christian @winsvega
I think the real problem I introduced Aug. 23, and involves not just PUSH1 but all the PUSH instructions no longer checking for the end of m_CodeSpace and generating zeros in that case. Reallocating and padding the bytecodes with zeros as Pawel does acomplishes the same task, at the cost of the reallocation.  So again, Pawel's fix is OK if we need to get past this quickly.  I'll be committing a better fix when it's ready.

**Comment by chfast** [comment]
My fix does not introduces additional relocation, but exploits the one that was there before. However, I suspect the copy in the line 59 https://github.com/ethereum/cpp-ethereum/pull/3334/files#diff-9acf316ae31a597007b278ef2ab430e8L59 was not neccesary in the first place.

File: libevm/VMOpt.cpp [hunk 1]
```diff
@@ -49,20 +49,22 @@ void VM::initMetrics()
...
 void VM::initEntry()
 {
-	m_bounce = &VM::interpretCases;	
+	m_bounce = &VM::interpretCases;
+
+	// Copy and extend code by 32 bytes to handle virtual push data.
+	auto extendedSize = m_ext->code.size() + 32;
+	m_codeSpace.reserve(extendedSize);
 	m_codeSpace = m_ext->code;
+	m_codeSpace.resize(extendedSize);
```
Comment (gcolvin) [inline libevm/VMOpt.cpp]: Alternatively, we can but put back code to pad on the fly
https://github.com/ethereum/cpp-ethereum/blob/push-beyond-limits/libevm/VM.cpp#L774

**Comment by gcolvin** [comment]
@chfast @christian @winsvega
There remains the question of why we bother stripping trailing zeros at all.  Seems that if the last instruction executed is a PUSH at the end of the code then the contract is going to halt with an invalid opcode in the next step anyway.  So we go to a lot of work for a few bytes of compression of some invalid contracts.

**Comment by chfast** [comment]
@gcolvin This "stripping" does not come from any preprocessing but from EVM spec. The code in the EVM is assumed to infinite length filled with zeros. User is allowed to modify some of the first bytes. Zero usually means STOP, except for if it is a push data.

**Comment by chriseth** [comment]
I would prefer reverting to the original solution, this fix seems like we could miss it in some other cases.

**Comment by gcolvin** [comment]
@chfast Aha, no physical bytes are actually stripped, just conceptual ones. (And the machine halts normally after executing the useless PUSH, not with invalid opcode.)  IMHO it's better the small number of conceptually infinite zero bytes the machine needs to stop gracefully are made physically present (which is what your fix does) rather than synthesized on the fly.
@chriseth Now that I understand it, Pawel's fix is the most efficient, and if 33 rather than 32 bytes were added would also let us eventually simplify a line in fetchInstruction() from
`		m_op = Instruction(m_pc < m_codeSpace.size() ? m_code[m_pc] : 0);
`
to
`		m_op = Instruction(m_code[m_pc]);
`
Where the Instruction() cast costs nothing.  This line is executed for every instruction executed.  I believe there are no other cases, though of course further testing and inspection is in order.  I we decide otherwise I can make a PR for https://github.com/ethereum/cpp-ethereum/blob/push-beyond-limits/libevm/VM.cpp#L774 when it finishes testing.
I think we should merge Pawel's fix.

**Comment by chfast** [comment]
There should be 3 cases:
1. "Virtual" push data. We have a lots of test for that.
2. "Virtual" stop instruction - conceptually if you run out of code it means STOP. But that might be implemented differently, e.g. using valid code iterators. Special subcase is a valid jump to JUMPDEST being at the very end of the code. We should check if we have tests for that.
3. Jump to the index out of the code. This means "invalid jump" because the destination is STOP not JUMPDEST. This is probably handled by jump implementation. I suspect we have tests for that.

**Comment by gcolvin** [comment]
The first two cases your fix can handle.  The third case is handled by constructing a lookup table of  valid jump destinations before the code is run.

**Comment by chriseth** [comment]
Right, actually adding zeros will allow us to remove some special cases - is it actually faster? The problem is that we have to take care that these zeroes are actually always added, this might be dangerous, but it could be fine to add a comment.

**Comment by gcolvin** [comment]
It should be a bit faster - it can save a bounds check for every byte 
pushed and every instruction fetched.  And yes, comments are good.

**Comment by chfast** [comment]
@winsvega Can you add of check if already exists a very simples test with code `PUSH32`, literally `0x7f`. This should be enough to check if a VM correctly handles 33 additional "virtual" bytes -- 32 for push data, 1 for STOP.

@chriseth Any opinions about merging this in?

File: libevm/VMOpt.cpp [hunk 2]
```diff
@@ -49,20 +49,22 @@ void VM::initMetrics()
...
-// init interpreter on entry
-//
-
+/// Init interpreter on entry.
 void VM::initEntry()
 {
-	m_bounce = &VM::interpretCases;	
+	m_bounce = &VM::interpretCases;
+
+	// Copy and extend code by 32 bytes to handle virtual push data.
```
Comment (chriseth) [inline libevm/VMOpt.cpp]: Please extend the comment:
```
Copy and extend code by 32 zero bytes to allow reading virtual push data at the end of the code without bounds checks.
```

Comment (chriseth) [inline libevm/VMOpt.cpp]: Also I don't see where this actually copies the code. Furthermore, doesn't `m_codeSpace.resize(extendedSize)` imply a reserve of (at least) the same size?

Comment (gcolvin) [inline libevm/VMOpt.cpp]: @chriseth the copy happens in the assignment on line 60.  My line comments above explain what is happening, I think, so could be pulled into the comment.  And of course Pawel knows what he was doing.  It should be 33 bytes, not 32, as @chfast said yesterday.

Comment (chfast) [inline libevm/VMOpt.cpp]: Comment updated.

reserve() allocates memory, but vector's size is 0, `=` copies one vector data to the second one, resize() fills the additional bytes with zero. We can't do much to make it look better and being optimal.

I also added a VM tests for PUSH32 without anything after it. We don't need 33 bytes because the "virtual STOP" is handled by `VM::fetchInstruction()` in https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/VM.cpp#L110.

**Comment by gcolvin** [comment]
Nice, @chfast.  33 bytes, please?

**Comment by chfast** [comment]
@gcolvin I don't understand why you want 33 bytes now. It is not needed to fix the VM. If you want to use it later to optimized fetchInstruction() it should be in a separated PR. I can take that on me.

**Comment by gcolvin** [comment]
OK.  I should do it later of it proves advantageous.
