### PR TITLE
Fixed exception constructor for msvc

### LINKED ISSUE #1323: UPnP: Debug Assertion Failed when trying to run eth command line client built from source in Windows
Getting Debug Assertion Failed followed by null pointer crash while running fresh-built "eth" command line client.

It looks like related issue:

Debug Assertion Failed!

Program: C:\Windows\system32\MSVCP120D.dll
File: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xstring
Line: 1168

Expression: invalid null pointer

I am on git version with latest commit 1e0201142f1e581a0d1c616f98091cc2e12dc85e , using Debug configuration, crashes unconditionally in UPnP:UPnP() constructor: 

	{
		cnote << "UPnP device not found.";
		BOOST_THROW_EXCEPTION(NoUPnPDevice()); // << Crashes here
	}

Attempt to continue leads to 

Unhandled exception at 0x012FCCBE in eth.exe: 0xC0000005: Access violation reading location 0x00000000.

It is worth to note that ETH_MINIUPNPC is NOT defined.

Stack trace of null pointer crash is:

>	eth.exe!std::char_traits<char>::length(const char * _First) Line 523	C++
 	eth.exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign(const char * _Ptr) Line 1169	C++
 	eth.exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >(const char * _Ptr) Line 783	C++
 	eth.exe!dev::NoUPnPDevice::NoUPnPDevice()	C++
 	eth.exe!dev::p2p::UPnP::UPnP() Line 91	C++
 	eth.exe!dev::p2p::Network::traverseNAT(const std::vector<boost::asio::ip::address,std::allocator<boost::asio::ip::address> > & _ifAddresses, unsigned short _listenPort, boost::asio::ip::address & o_upnpifaddr) Line 154	C++
 	eth.exe!dev::p2p::Host::determinePublic(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & _publicAddress, bool _upnp) Line 327	C++
 	eth.exe!dev::p2p::Host::startedWorking() Line 605	C++
 	eth.exe!dev::Worker::startWorking::__l9::<lambda>() Line 41	C++

Configuration: Windows 7 64-bit running within VMWare Workstation, bridged network, rouner pfSense with uPnP disabled, yet I do not think network config is relevant in this case.

### PR DESCRIPTION
**Pull request by arkpar**
compiler bug workaround
http://stackoverflow.com/questions/21044488/known-compiler-bug-in-vc12
Fixes #1323 and #1303

### CODE REVIEW

File: libdevcore/Exceptions.h [hunk 1]
```diff
@@ -33,7 +33,7 @@ namespace dev
 // base class for all exceptions
 struct Exception: virtual std::exception, virtual boost::exception
 {
-	Exception(std::string _message = {}): m_message(std::move(_message)) {}
+	Exception(std::string _message = std::string()): m_message(std::move(_message)) {}
```
Comment (chfast) [inline libdevcore/Exceptions.h]: I prefer `= std::string{}`.
