### PR TITLE
Ethereumjs

### LINKED ISSUE #815: cmake building ethereumjs gives ENOENT error on dist/ethereum.js.map
```
> ethereum.js@0.0.7 build /private/tmp/ethereum-JyBLsf/libjsqrc/ethereumjs
> gulp
 
[15:16:21] Using gulpfile /private/tmp/ethereum-JyBLsf/libjsqrc/ethereumjs/gulpfile.js
[15:16:21] Starting 'bower'...
[15:16:21] Starting 'lint'...
[15:16:24] Finished 'lint' after 3 s
[15:16:24] Starting 'clean'...
[15:16:24] Finished 'clean' after 12 ms
[15:16:24] Starting 'buildDev'...
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/ethereum-JyBLsf/CMakeFiles 39
[ 11%] Building CXX object libevmcore/CMakeFiles/evmcore.dir/Instruction.cpp.o
cd /tmp/ethereum-JyBLsf/libevmcore && /usr/bin/clang++   -DETH_JSONRPC -DETH_MINIUPNPC -DETH_READLINE -Devmcore_EXPORTS -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -DSTATICLIB -O0 -g -DETH_DEBUG -fPIC -I/usr/local/include -I/tmp/ethereum-JyBLsf -I/tmp/ethereum-JyBLsf/libevmcore/..    -o CMakeFiles/evmcore.dir/Instruction.cpp.o -c /tmp/ethereum-JyBLsf/libevmcore/Instruction.cpp
 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'dist/ethereum.js.map'
 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "build"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code ELIFECYCLE
npm ERR! ethereum.js@0.0.7 build: `gulp`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ethereum.js@0.0.7 build script.
npm ERR! This is most likely a problem with the ethereum.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls ethereum.js
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/ethereum-JyBLsf/libjsqrc/ethereumjs/npm-debug.log
make[2]: *** [ethereumjs] Error 1
make[1]: *** [libjsqrc/CMakeFiles/ethereumjs.dir/all] Error 2
```

Full logs:
https://gist.github.com/anonymous/bf284b31007706dd358f#file-02-make-L395

d0f80eb441719d6ef889b94b1186d3a075bc1ee4 on OSX via brew

### PR DESCRIPTION
**Pull request by debris**
* moved `web3.contract` -> `web3.eth.contract`
* all abi types are now 32 bytes aligned
* tests for formatting abi types (not finished yet)
* separated `ProviderManager` and `Filter` to another files
* More comments in code
* big numbers support ([bignumber.js](https://github.com/MikeMcl/bignumber.js/))
* fixed #815 (gulpfile.js bug)
* negative values support
* floating point numbers are now rounded down, if there are passed as Int or UInt param to abi.js
* upgraded version to `0.0.8`
* fixed library usage with node.js
* fixed strings length
* parsing arrays by abi.js

TODO:
* fix array of strings, ureal, real types implementation && tests
* tests for wrongly formatted inputs or outputs

@gavofyork or @chriseth please verify that tests in `test/abi.parsers.js` are correct

### CODE REVIEW

File: libjsqrc/ethereumjs/lib/contract.js [hunk 1]
```diff
@@ -27,9 +27,29 @@ if (process.env.NODE_ENV !== 'build') {
...
 
+/**
+ * This method should be called when we want to call / transact some solidity method from javascript
+ * it returns an object which has same methods available as solidity contract description
+ * usage example: 
+ *
+ * var abi = [{
+ *      name: 'myMethod',
+ *      inputs: [{ name: 'a', type: 'string' }],
+ *      outputs: [{name 'd', type: 'string' }]
```
Comment (chriseth) [inline libjsqrc/ethereumjs/lib/contract.js]: Missing colon

File: libjsqrc/ethereumjs/lib/contract.js [hunk 2]
```diff
@@ -27,9 +27,29 @@ if (process.env.NODE_ENV !== 'build') {
...
+ * }];  // contract abi
+ *
+ * var myContract = web3.eth.contract('0x0123123121', abi); // creation of contract object
+ *
+ * myContract.myMethod('this is test string param for call').cal(); // myMethod call
```
Comment (chriseth) [inline libjsqrc/ethereumjs/lib/contract.js]: "cal" -> "call"

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 3]
```diff
@@ -1,37 +1,538 @@
...
+            // when
+            var parser = abi.inputParser(d);
+
+            // then
+            assert.equal(parser.test(1), "0000000000000000000000000000000000000000000000000000000000000001");
+            assert.equal(parser.test(10), "000000000000000000000000000000000000000000000000000000000000000a");
+
+        });
+        
+        it('should parse input uint', function() {
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: Test name seems incorrect

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 4]
```diff
@@ -1,37 +1,538 @@
...
+
+            d[0].inputs = [
+                { type: "int128" }
+            ];
+
+            // when
+            var parser = abi.inputParser(d);
+
+            // then
+            assert.equal(parser.test(1), "0000000000000000000000000000000000000000000000000000000000000001");
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: Please test it with a negative value.

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 5]
```diff
@@ -1,37 +1,538 @@
...
+
+            d[0].inputs = [
+                { type: "hash160" }
+            ];
+
+            // when
+            var parser = abi.inputParser(d);
+            
+            // then
+            assert.equal(parser.test("0x407d73d8a49eeb85d32cf465507dd71d507100c1"), "000000000000000000000000407d73d8a49eeb85d32cf465507dd71d507100c1");
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: What happens if you supply a hash here that does not fit into 160 bits?

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 6]
```diff
@@ -1,37 +1,538 @@
...
+
+            d[0].inputs = [
+                { type: "string" }
+            ];
+
+            // when
+            var parser = abi.inputParser(d);
+
+            // then
+            assert.equal(parser.test('hello'), "68656c6c6f000000000000000000000000000000000000000000000000000000");
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: It should be "056865..." (same amount of zeros): Since string has variable length, you have to prepend its length.
Note that this type is not supported by solidity yet, only the fixed-length strings up to 32 bytes.

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 7]
```diff
@@ -1,37 +1,538 @@
...
+
+            d[0].outputs = [
+                { type: "string" }
+            ];
+
+            // when
+            var parser = abi.outputParser(d);
+            
+            // then
+            assert.equal(parser.test("0x68656c6c6f000000000000000000000000000000000000000000000000000000")[0], 'hello');
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: Same for string as output

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 8]
```diff
@@ -1,37 +1,538 @@
...
+            assert.equal(parser.test("0x000000000000000000000000000000000000000000000000000000000000000a")[0], 10);
+        });
+
+        it('should parse output uint128', function() {
+
+            // given
+            var d = clone(description);
+
+            d[0].outputs = [
+                { type: 'uinti128' }
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: That test should not succeed...

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 9]
```diff
@@ -1,37 +1,538 @@
...
+            assert.equal(parser.test("0x000000000000000000000000000000000000000000000000000000000000000a")[0], 10);
+        });
+
+        it('should parse output int128', function() {
+
+            // given
+            var d = clone(description);
+
+            d[0].outputs = [
+                { type: 'inti128' }
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: again inti

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 10]
```diff
@@ -1,37 +1,538 @@
...
+            assert.equal(parser.test("0x000000000000000000000000407d73d8a49eeb85d32cf465507dd71d507100c1")[0], "0x000000000000000000000000407d73d8a49eeb85d32cf465507dd71d507100c1")
+        });
+
+        it('should parse output hash160', function() {
+            
+            // given
+            var d = clone(description);
+
+            d[0].outputs = [
+                { type: 'hash256' }
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: type is unchanged

File: libjsqrc/ethereumjs/test/abi.parsers.js [hunk 11]
```diff
@@ -1,37 +1,538 @@
...
+            d[0].outputs = [
+                { type: "string" },
+                { type: "string" }
+            ];
+
+            // when
+            var parser = abi.outputParser(d);
+
+            // then
+            assert.equal(parser.test("0x68656c6c6f000000000000000000000000000000000000000000000000000000776f726c64000000000000000000000000000000000000000000000000000000")[0], 'hello');
```
Comment (chriseth) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: That should be "0x050568...000776...00".

**Comment by chriseth** [comment]
I basically had a look at the tests. What is missing apart from the comments above is perhaps tests for wrongly formatted inputs or outputs, e.g. floats with values different from 0 or 1 or a uint8 with higher bits not set to zero.

File: libjsqrc/ethereumjs/test/abi.parsers.js (hunk 10 above)
Comment (debris) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: fixed

File: libjsqrc/ethereumjs/test/abi.parsers.js (hunk 4 above)
Comment (debris) [inline libjsqrc/ethereumjs/test/abi.parsers.js]: i added negative value support and tests

**Comment by debris** [comment]
@chriseth i addressed part of your issues (i updated PR description), the rest will be addressed in next commits. please review again :)

**Comment by gavofyork** [comment]
rebase?
