### PR TITLE
Fixed checking of abstract functions.

### LINKED ISSUE #2264: solc segfaults when derived contract implements an abstract function with wrong argument types
solc segfaults when a derived contract implements an abstract function with wrong argument types.

example:
contract base { function foo(uint256 arg0); }
contract derived is base { function foo() {} }

result:
Segmentation fault: 11

An error message would be more helpful.

### PR DESCRIPTION
**Pull request by chriseth**
Previous implementation did not handle function overloading correctly.

Fixes #2264

### CODE REVIEW

**Comment by arkpar** [comment]
needs rebase to check windows build

**Comment by chriseth** [comment]
Oops, missed that comment. Rebased.

File: libsolidity/AST.cpp [hunk 1]
```diff
@@ -175,24 +175,40 @@ void ContractDefinition::checkDuplicateFunctions() const
...
 	// Search from base to derived
 	for (ContractDefinition const* contract: boost::adaptors::reverse(getLinearizedBaseContracts()))
 		for (ASTPointer<FunctionDefinition> const& function: contract->getDefinedFunctions())
 		{
-			string const& name = function->getName();
-			if (!function->isFullyImplemented() && functions.count(name) && functions[name])
-				BOOST_THROW_EXCEPTION(function->createTypeError("Redeclaring an already implemented function as abstract"));
-			functions[name] = function->isFullyImplemented();
+			auto& overloads = functions[function->getName()];
+			FunctionTypePointer funType = make_shared<FunctionType>(*function);
```
Comment (subtly) [inline libsolidity/AST.cpp]: What happens to m_definedFunctions[x] when funType is deallocated?

Comment (subtly) [inline libsolidity/AST.cpp]: nvm.
